sudo: required
dist: Bionic Beaver
language: python
virtualenv:

  system_site_packages: true
python:
- '3.5'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~
deploy:
  provider: pypi
  user: JaviMancilla
  password:
    secure: a1HSrEaBY1Gba6SF/Kl2L2bz5TSnqwWcqatGmiGbTj6XskiSXvcsDiEIS+oT3TGuVzknt01MjJ8dJWea7s2DJgER4Oc7KMow1u2JAs0pOyVqi1LKgoNPgoH9n/nr5E39T/lyFPtDN5blVnjuSCfRPLFBd+eHxdBbsRNLlLGTAy80j7JQOenzwW8ofvTNH9QETdn9hr/dUMgKMGw3bdaKYLXQDDV4SLWxeVN4Nyjzn+0UUyLlipSBYGfVB1RVNsZF7wPbGhkrz+pQmA+W39f98QMEIZuoQfMooiCQ6INEGC66dBMP3xjWCH3xCphBGY60iaaYYZdiVsVgrlKWEI+qJ0S9cAsahJvbttMlKT7tb39UcSBfSiQYTyJSLHinW/LWe4JlWl3h3lT3wI5KBupXTXq2cIVPGqyr7L8e5XApdBRKXFmJPM6XQoTUCKutMaz3lp0FLCZfw80P6qiK1koVGyCKAor7y+KcUd1QLIKeFIJ2jUyro8GFgtQlF+gaWRTqhtzP0oy3hbZpx4wQeU8vEfPWnRWXqZ2nymVTuU8q25IsYfxwcyIjF8RaiXkJJ1gIPfGWr2HoOA2v/ap9RQ3g73gT4KYfSOqZMEotNEPvqKclITEYS/jdBdTEoxX99uYSTl6hgRSyM+I1rrilOLHeMPxtcNVTM9hazHAadN52CbU=
